version: '3.8'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  postgres-data:
    driver: local

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - mindswap-net

  marketplace-service:
    build: .
    container_name: marketplace-service
    depends_on:
      - mindswap-postgres
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mindswap-postgres:5432/marketplace_api
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
      SERVER_PORT: '8081'
      SPRING_PROFILES_ACTIVE: 'docker'
      SPRING_DATA_SOURCE: org.postgresql.Driver
      HIBERNATE_DDL_AUTO: 'none'
    networks:
      - mindswap-net

  mindswap-postgres:
    image: postgres:latest
    container_name: mindswap-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mindswap-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - mindswap-net

networks:
  mindswap-net:
    driver: bridge


