spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace_api
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: true
      show-sql: true
    database: postgresql

  flyway:
    locations: classpath:db/migration/
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    out-of-order: true
    ignore-migration-patterns: "*:ignored"

  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5

server:
  port: 8081

# SpringDoc OpenAPI settings
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"