management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: true


    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

server:
  port: 8081

